#!/bin/bash

info() {
    echo -e "\n\e[1;33m--> $1\e[0m"
}

error() {
    echo -e "\e[1;31merror: $1\e[0m" >&2
}

# check for root
if [ $(id -u) != 0 ]; then
    error "must be root"
    exit 255
fi

# update everything
info "upgrading system and installing ifplugd, wpa_actiond and sudo"
yes | pacman -Syu ifplugd wpa_actiond sudo

# reconfigure networks
find /etc/systemd/system -name 'netctl*' -print -delete
for dev in /sys/class/net/*; do
    dev=$(basename $dev)
    info "enabling automatic for device $dev"
    case $dev in
        eth*)   systemctl enable netctl-ifplugd@$dev.service ;;
        wlan*)  systemctl enable netctl-auto@$dev.service ;;
    esac
done

# set sudoers
info "allowing wheel users to use sudo"
echo '%wheel ALL=(ALL) NOPASSWD: ALL' > $MOUNT/etc/sudoers.d/wheel

# fix packages with setcap - maybe this happens only when using tar instead of bsdtar?
#info "reinstalling packages with binaries with missing capabilities"
#yes | pacman -Sw $(pacman -Q | awk '{ print $1 }')

# install and enable ntp
info "installing ntp"
yes | pacman -S ntp
ntpdate $(awk '/^server / { print $2 }' /etc/ntpd.conf)
systemctl enable --now ntpd

# change alarm and root passwords

# install some more packages
info "installing some more packages"
yes | pacman -S \
    htop \
    lsof \
    mc \
    strace \
    tmux \
    vim

# set $EDITOR to vim as god intended
info "configuring editor"
echo 'export EDITOR=vim' > /etc/profile.d/editor.sh

# configure htop for a little
cat >/etc/htoprc <<EOF
hide_threads=0
hide_kernel_threads=1
hide_userland_threads=1
highlight_base_name=1
tree_view=1
header_margin=1
detailed_cpu_time=1
cpu_count_from_zero=1
update_process_names=1
account_guest_in_cpu_meter=0
color_scheme=5
EOF
