#!/bin/bash

info() {
    echo -e "\n\e[1;33m--> $1\e[0m"
}

error() {
    echo -e "\e[1;31merror: $1\e[0m" >&2
}

# check for root
if [ $(id -u) != 0 ]; then
    error "must be root"
    exit 255
fi

# update everything
info "upgrading system and installing ifplugd, wpa_actiond and sudo"
yes | pacman -Syu ifplugd wpa_actiond sudo

# reconfigure networks
#find /etc/systemd/system -name 'netctl*' -print -delete
for prof in /etc/netctl/*; do
    if [ -f "$prof" ]; then
        prof=$(basename $prof)
        info "disabling network profile $prof"
        netctl disable $prof
    fi
done
for dev in /sys/class/net/*; do
    dev=$(basename $dev)
    info "enabling automatic for device $dev"
    case $dev in
        eth*)   systemctl enable netctl-ifplugd@$dev.service ;;
        wlan*)  systemctl enable netctl-auto@$dev.service ;;
    esac
done

# set sudoers
info "allowing wheel users to use sudo"
echo '%wheel ALL=(ALL) NOPASSWD: ALL' > $MOUNT/etc/sudoers.d/wheel

# fix packages with setcap
# install and enable ntp
info "installing ntp"
yes | pacman -S ntp
ntpdate $(awk '/^server / { print $2 }' /etc/ntpd.conf)
systemctl enable --now ntpd

# change alarm and root passwords

# install some more packages
info "installing some more packages"
yes | pacman -S htop lsof strace mc
