#!/bin/bash

TARGET=${1:?Missing target disk}
IMAGE=${2:?Missing version, such as ArchLinuxARM-rpi-latest.tar.gz or ArchLinuxARM-rpi-2-latest.tar.gz}

info() {
    echo -e "\n\e[1;33m--> $1\e[0m"
}

error() {
    echo -e "\e[1;31merror: $1\e[0m" >&2
}

# check for root
if [ $(id -u) != 0 ]; then
    error "must be root"
    exit 255
fi

# check target device exists
if ! lsblk $TARGET &> /dev/null; then
    error "$TARGET does not seem to exist"
    exit 255
fi

# check target device is not mounted
if mount | grep -q $TARGET; then
    error "$TARGET seems to be mounted"
    exit 255
fi

# check we have everything
for cmd in curl gpg mkfs.vfat; do
    if ! type -p $cmd &> /dev/null; then
        error "going to need $cmd, make sure it is installed"
        exit 255
    fi
done

if [ ! -f "$IMAGE" ]; then
    info "downloading $IMAGE..."
    curl -L "http://os.archlinuxarm.org/os/$IMAGE" -o "$IMAGE" || exit 1
    curl -L "http://os.archlinuxarm.org/os/$IMAGE.sig" -o "$IMAGE.sig" -s || exit 1
else
    info "trying to download newer version of $IMAGE"
    curl -L "http://os.archlinuxarm.org/os/$IMAGE" -o "$IMAGE" -z "$IMAGE" || exit 2
    curl -L "http://os.archlinuxarm.org/os/$IMAGE.sig" -o "$IMAGE.sig" -z "$IMAGE.sig" -s || exit 2
fi

info "checking for builder@archlinuxarm.org public key"
if ! gpg --list-public-keys | grep -q 68B3537F39A313B3E574D06777193F152BDBE6A6; then
    info "receiving builder@archlinuxarm.org public key"
    gpg --recv-keys 68B3537F39A313B3E574D06777193F152BDBE6A6 || exit 3
fi

if [ "$VERIFY" != "0" ]; then
    info "verifying signature"
    gpg --verify $IMAGE.sig $IMAGE || exit 4
fi

info "partitioning $TARGET"
sfdisk $TARGET --delete || exit 5
echo -e ",$[512*2048]b\n,,83" | sfdisk $TARGET || exit 6

# disable systemd-{networkd,resolved,timesyncd}
# create empty resolv.conf
# set hostname
# set timezone
# set locale
# install and enable netctl profiles
# set sudoers

# fix packages with setcap
# install and enable ntp


